# practice Numpy - Jaoyad

**Valid Sudoku**

In [10]:
%pip install numpy
import numpy as np

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

**General Questions**

In [12]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [13]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [14]:
#Find the average age of students.
data_mean = np.mean(data)
data_mean

np.float64(61.06666666666667)

In [15]:
#Extract Math marks of all students.
data_math = data[:,1]
data_math

array([85, 92, 76, 65, 90])

In [17]:
#Find the highest Science mark.
data_sci = data[:, 2]
print('All science marks', data_sci)


sci_max = np.max(data_sci)
print('highest mark', sci_max)

All science marks [78 88 95 70 85]
highest mark 95


In [19]:
#Get details of the student who scored more than 90 in Math.

student = data[data[:,1] > 90]
print('Details who scored more than 90 in math ',student)

Details who scored more than 90 in math  [[19 92 88]]


In [23]:
#Increase Math marks of all students by 5.
extra_mark = 5

increased_mark = data[:,1] + 5

print('after added 5 marks in math ',increased_mark)
print('whole data ',data)

after added 5 marks in math  [90 97 81 70 95]
whole data  [[18 85 78]
 [19 92 88]
 [17 76 95]
 [18 65 70]
 [20 90 85]]


In [27]:
#Find how many students are younger than 19.
student_age = data[data[:,0] < 19]

print('younger than 19 => ',len(student_age))

younger than 19 =>  3


In [29]:
#Calculate the average marks in each subject (column-wise mean).
total_math = data[:, 1]
total_sci = data[:, 2]

print('total marks in math ', total_math.sum())
print('total marks in science ', total_sci.sum())

total marks in math  408
total marks in science  416


In [34]:
#Get data of students who scored at least 80 in both subjects.
the_condition = (data[:,1] >= 80) & (data[:,2] >= 80)

ultimate_stu = data[the_condition]

print('students who scored atleast 80 in both => ', len(ultimate_stu))

students who scored atleast 80 in both =>  2


In [35]:
#Replace all Science marks < 75 with 0.

data[data[:,2] < 75, 2] = 0

print('after replacing these values ', data)

after replacing these values  [[18 85 78]
 [19 92 88]
 [17 76 95]
 [18 65  0]
 [20 90 85]]


# The end of practice